/**
 * playerData.js
 * -----------------------------------------------------------------------------
 * The raw player pool. Rows are compact tuples to keep the file readable:
 *
 *   [ name, position, nflTeam, projectedPoints ]
 *
 * Projections are synthetic sample data for demo/testing purposes — swap this
 * module for a fetch() against your projections API and nothing else changes.
 */

/** @type {Array<[string, string, string, number]>} */
export const RAW_PLAYERS = [
  // ---------------------------------------------------------------- QB ------
  ['Josh Allen', 'QB', 'BUF', 385],
  ['Lamar Jackson', 'QB', 'BAL', 380],
  ['Jalen Hurts', 'QB', 'PHI', 372],
  ['Jayden Daniels', 'QB', 'WAS', 368],
  ['Patrick Mahomes', 'QB', 'KC', 360],
  ['Joe Burrow', 'QB', 'CIN', 355],
  ['C.J. Stroud', 'QB', 'HOU', 340],
  ['Kyler Murray', 'QB', 'ARI', 335],
  ['Justin Herbert', 'QB', 'LAC', 330],
  ['Brock Purdy', 'QB', 'SF', 325],
  ['Dak Prescott', 'QB', 'DAL', 322],
  ['Baker Mayfield', 'QB', 'TB', 320],
  ['Caleb Williams', 'QB', 'CHI', 318],
  ['Bo Nix', 'QB', 'DEN', 315],
  ['Jared Goff', 'QB', 'DET', 312],
  ['Tua Tagovailoa', 'QB', 'MIA', 305],
  ['Trevor Lawrence', 'QB', 'JAX', 300],
  ['Drake Maye', 'QB', 'NE', 298],
  ['Anthony Richardson', 'QB', 'IND', 295],
  ['Matthew Stafford', 'QB', 'LAR', 292],
  ['Geno Smith', 'QB', 'SEA', 288],
  ['Aaron Rodgers', 'QB', 'NYJ', 285],
  ['Kirk Cousins', 'QB', 'ATL', 280],
  ['Derek Carr', 'QB', 'NO', 272],
  ['J.J. McCarthy', 'QB', 'MIN', 265],
  ['Will Levis', 'QB', 'TEN', 258],

  // ---------------------------------------------------------------- RB ------
  ['Bijan Robinson', 'RB', 'ATL', 305],
  ['Saquon Barkley', 'RB', 'PHI', 300],
  ['Jahmyr Gibbs', 'RB', 'DET', 295],
  ['Christian McCaffrey', 'RB', 'SF', 290],
  ['Derrick Henry', 'RB', 'BAL', 285],
  ['Breece Hall', 'RB', 'NYJ', 275],
  ["De'Von Achane", 'RB', 'MIA', 272],
  ['Ashton Jeanty', 'RB', 'LV', 268],
  ['Josh Jacobs', 'RB', 'GB', 265],
  ['Jonathan Taylor', 'RB', 'IND', 262],
  ['Bucky Irving', 'RB', 'TB', 255],
  ['Kyren Williams', 'RB', 'LAR', 252],
  ['Chase Brown', 'RB', 'CIN', 248],
  ['James Cook', 'RB', 'BUF', 245],
  ['Kenneth Walker III', 'RB', 'SEA', 240],
  ['Omarion Hampton', 'RB', 'LAC', 235],
  ['Chuba Hubbard', 'RB', 'CAR', 232],
  ['Alvin Kamara', 'RB', 'NO', 230],
  ['James Conner', 'RB', 'ARI', 228],
  ['Joe Mixon', 'RB', 'HOU', 226],
  ['David Montgomery', 'RB', 'DET', 215],
  ['Brian Robinson Jr.', 'RB', 'WAS', 210],
  ['Tony Pollard', 'RB', 'TEN', 208],
  ['Aaron Jones', 'RB', 'MIN', 206],
  ['RJ Harvey', 'RB', 'DEN', 200],
  ['TreVeyon Henderson', 'RB', 'NE', 198],
  ['Quinshon Judkins', 'RB', 'CLE', 195],
  ['Isiah Pacheco', 'RB', 'KC', 193],
  ['Tyrone Tracy Jr.', 'RB', 'NYG', 190],
  ["D'Andre Swift", 'RB', 'CHI', 188],
  ['Rhamondre Stevenson', 'RB', 'NE', 182],
  ['Javonte Williams', 'RB', 'DAL', 178],
  ['Najee Harris', 'RB', 'LAC', 176],
  ['Travis Etienne Jr.', 'RB', 'JAX', 174],
  ['Jaylen Warren', 'RB', 'PIT', 172],
  ['Rachaad White', 'RB', 'TB', 168],
  ['Zach Charbonnet', 'RB', 'SEA', 165],
  ['Tyjae Spears', 'RB', 'TEN', 160],
  ['Jordan Mason', 'RB', 'MIN', 158],
  ['Cam Skattebo', 'RB', 'NYG', 155],
  ['Braelon Allen', 'RB', 'NYJ', 150],
  ['Kaleb Johnson', 'RB', 'PIT', 148],
  ['Trey Benson', 'RB', 'ARI', 145],
  ['Jaydon Blue', 'RB', 'DAL', 140],
  ['Bhayshul Tuten', 'RB', 'JAX', 138],
  ['Roschon Johnson', 'RB', 'CHI', 132],
  ['Nick Chubb', 'RB', 'HOU', 130],
  ['Austin Ekeler', 'RB', 'WAS', 128],
  ['Rico Dowdle', 'RB', 'CAR', 126],
  ['Tank Bigsby', 'RB', 'JAX', 122],
  ['Jerome Ford', 'RB', 'CLE', 120],
  ['Ray Davis', 'RB', 'BUF', 118],
  ['Blake Corum', 'RB', 'LAR', 115],
  ['Isaac Guerendo', 'RB', 'SF', 112],
  ['Jaylen Wright', 'RB', 'MIA', 110],
  ['Will Shipley', 'RB', 'PHI', 105],
  ['Sean Tucker', 'RB', 'TB', 100],
  ['Dylan Sampson', 'RB', 'CLE', 98],
  ['Kendre Miller', 'RB', 'NO', 95],
  ['Devin Neal', 'RB', 'NO', 92],

  // ---------------------------------------------------------------- WR ------
  ["Ja'Marr Chase", 'WR', 'CIN', 330],
  ['Justin Jefferson', 'WR', 'MIN', 315],
  ['CeeDee Lamb', 'WR', 'DAL', 305],
  ['Malik Nabers', 'WR', 'NYG', 295],
  ['Puka Nacua', 'WR', 'LAR', 290],
  ['Amon-Ra St. Brown', 'WR', 'DET', 288],
  ['Nico Collins', 'WR', 'HOU', 280],
  ['Brian Thomas Jr.', 'WR', 'JAX', 278],
  ['Drake London', 'WR', 'ATL', 272],
  ['A.J. Brown', 'WR', 'PHI', 270],
  ['Tee Higgins', 'WR', 'CIN', 262],
  ['Ladd McConkey', 'WR', 'LAC', 258],
  ['Tyreek Hill', 'WR', 'FA', 255],
  ['Garrett Wilson', 'WR', 'NYJ', 252],
  ['Davante Adams', 'WR', 'LAR', 248],
  ['Mike Evans', 'WR', 'TB', 245],
  ['Marvin Harrison Jr.', 'WR', 'ARI', 242],
  ['Terry McLaurin', 'WR', 'WAS', 238],
  ['DK Metcalf', 'WR', 'PIT', 235],
  ['Jaxon Smith-Njigba', 'WR', 'SEA', 232],
  ['Rashee Rice', 'WR', 'KC', 228],
  ['Courtland Sutton', 'WR', 'DEN', 225],
  ['Jerry Jeudy', 'WR', 'CLE', 222],
  ['Zay Flowers', 'WR', 'BAL', 220],
  ['DJ Moore', 'WR', 'CHI', 218],
  ['Jaylen Waddle', 'WR', 'MIA', 215],
  ['Xavier Worthy', 'WR', 'KC', 212],
  ['George Pickens', 'WR', 'DAL', 210],
  ['Rome Odunze', 'WR', 'CHI', 206],
  ['Chris Godwin', 'WR', 'TB', 204],
  ['Travis Hunter', 'WR', 'JAX', 200],
  ['Jameson Williams', 'WR', 'DET', 198],
  ['Calvin Ridley', 'WR', 'TEN', 195],
  ['Tetairoa McMillan', 'WR', 'CAR', 192],
  ['Jordan Addison', 'WR', 'MIN', 190],
  ['Khalil Shakir', 'WR', 'BUF', 186],
  ['Ricky Pearsall', 'WR', 'SF', 182],
  ['Deebo Samuel', 'WR', 'WAS', 180],
  ['Jakobi Meyers', 'WR', 'LV', 178],
  ['Stefon Diggs', 'WR', 'NE', 175],
  ['Keon Coleman', 'WR', 'BUF', 172],
  ['Emeka Egbuka', 'WR', 'TB', 170],
  ['Josh Downs', 'WR', 'IND', 166],
  ['Matthew Golden', 'WR', 'GB', 164],
  ['Jayden Reed', 'WR', 'GB', 162],
  ['Chris Olave', 'WR', 'NO', 160],
  ['Darnell Mooney', 'WR', 'ATL', 156],
  ['Cooper Kupp', 'WR', 'SEA', 154],
  ['Michael Pittman Jr.', 'WR', 'IND', 152],
  ['Rashid Shaheed', 'WR', 'NO', 148],
  ['Jauan Jennings', 'WR', 'SF', 145],
  ["Wan'Dale Robinson", 'WR', 'NYG', 142],
  ['Cedric Tillman', 'WR', 'CLE', 138],
  ['Marvin Mims Jr.', 'WR', 'DEN', 135],
  ['Luther Burden III', 'WR', 'CHI', 132],
  ['Quentin Johnston', 'WR', 'LAC', 130],
  ['Adam Thielen', 'WR', 'CAR', 126],
  ['Tre Harris', 'WR', 'LAC', 124],
  ['Christian Kirk', 'WR', 'HOU', 122],
  ['Brandon Aiyuk', 'WR', 'SF', 120],
  ['Hollywood Brown', 'WR', 'KC', 118],
  ['Jalen McMillan', 'WR', 'TB', 115],
  ['Romeo Doubs', 'WR', 'GB', 112],
  ['DeMario Douglas', 'WR', 'NE', 108],
  ['Alec Pierce', 'WR', 'IND', 105],
  ['Dontayvion Wicks', 'WR', 'GB', 102],
  ['Kayshon Boutte', 'WR', 'NE', 100],
  ['Xavier Legette', 'WR', 'CAR', 98],
  ['Andrei Iosivas', 'WR', 'CIN', 95],
  ['Elic Ayomanor', 'WR', 'TEN', 92],

  // ---------------------------------------------------------------- TE ------
  ['Brock Bowers', 'TE', 'LV', 225],
  ['Trey McBride', 'TE', 'ARI', 215],
  ['George Kittle', 'TE', 'SF', 205],
  ['Sam LaPorta', 'TE', 'DET', 190],
  ['Travis Kelce', 'TE', 'KC', 185],
  ['Mark Andrews', 'TE', 'BAL', 178],
  ['T.J. Hockenson', 'TE', 'MIN', 172],
  ['David Njoku', 'TE', 'CLE', 168],
  ['Evan Engram', 'TE', 'DEN', 160],
  ['Tucker Kraft', 'TE', 'GB', 155],
  ['Dalton Kincaid', 'TE', 'BUF', 150],
  ['Jonnu Smith', 'TE', 'PIT', 146],
  ['Colston Loveland', 'TE', 'CHI', 140],
  ['Tyler Warren', 'TE', 'IND', 138],
  ['Hunter Henry', 'TE', 'NE', 132],
  ['Zach Ertz', 'TE', 'WAS', 128],
  ['Dallas Goedert', 'TE', 'PHI', 125],
  ['Cade Otton', 'TE', 'TB', 120],
  ['Isaiah Likely', 'TE', 'BAL', 118],
  ['Kyle Pitts', 'TE', 'ATL', 115],
  ['Brenton Strange', 'TE', 'JAX', 110],
  ['Chig Okonkwo', 'TE', 'TEN', 105],
  ['Pat Freiermuth', 'TE', 'PIT', 102],
  ['Mike Gesicki', 'TE', 'CIN', 98],

  // ----------------------------------------------------------------- K ------
  ['Brandon Aubrey', 'K', 'DAL', 165],
  ['Cameron Dicker', 'K', 'LAC', 152],
  ['Chris Boswell', 'K', 'PIT', 150],
  ['Jake Bates', 'K', 'DET', 148],
  ['Harrison Butker', 'K', 'KC', 145],
  ["Ka'imi Fairbairn", 'K', 'HOU', 143],
  ['Tyler Bass', 'K', 'BUF', 140],
  ['Jason Sanders', 'K', 'MIA', 136],
  ['Younghoe Koo', 'K', 'ATL', 134],
  ['Evan McPherson', 'K', 'CIN', 132],
  ['Wil Lutz', 'K', 'DEN', 130],
  ['Jake Elliott', 'K', 'PHI', 128],
  ['Matt Gay', 'K', 'WAS', 124],
  ['Cairo Santos', 'K', 'CHI', 120],

  // --------------------------------------------------------------- DST ------
  ['Broncos D/ST', 'DST', 'DEN', 145],
  ['Eagles D/ST', 'DST', 'PHI', 140],
  ['Ravens D/ST', 'DST', 'BAL', 138],
  ['Texans D/ST', 'DST', 'HOU', 135],
  ['Steelers D/ST', 'DST', 'PIT', 132],
  ['Bills D/ST', 'DST', 'BUF', 128],
  ['Vikings D/ST', 'DST', 'MIN', 126],
  ['Lions D/ST', 'DST', 'DET', 124],
  ['Packers D/ST', 'DST', 'GB', 122],
  ['Chiefs D/ST', 'DST', 'KC', 120],
  ['Seahawks D/ST', 'DST', 'SEA', 118],
  ['Chargers D/ST', 'DST', 'LAC', 115],
  ['49ers D/ST', 'DST', 'SF', 112],
  ['Buccaneers D/ST', 'DST', 'TB', 108]
];

/**
 * Normalises the tuple rows into Player-shaped objects with stable ids.
 * VOR fields are left at their defaults — `vorMath.enrichPlayers()` fills them.
 * @returns {import('./types.js').Player[]}
 */
export function loadPlayers() {
  return RAW_PLAYERS.map(([name, position, team, projection], index) => ({
    id: `p-${String(index).padStart(4, '0')}`,
    name,
    position,
    team,
    projection,
    vor: 0,
    vorRank: 0,
    posRank: 0,
    tier: 1,
    adp: 0,
    draftedBy: null,
    pickNumber: null
  }));
}
