/**
 * scripts/build-api.mjs
 * -----------------------------------------------------------------------------
 * Bundles the Vercel Function: lib/api/syncRoute.ts -> api/sync.js.
 *
 * Why a build step for this one file, in a project that otherwise has none:
 * Vercel's TypeScript step compiles the function entrypoint but leaves its
 * `.ts` import specifiers alone and does not trace them, so a deployed
 * `api/sync.ts` dies at runtime with
 *
 *   ERR_MODULE_NOT_FOUND: Cannot find module '/var/task/lib/services/sportsData.ts'
 *
 * esbuild resolves those specifiers and inlines the service into one ESM file,
 * so the function carries no dependency on runtime type stripping or on module
 * tracing. Nothing else in the project needs building: the browser app is
 * static, and the CLI and tests import the `.ts` modules directly.
 *
 * `api/sync.js` is committed even though Vercel rebuilds it on deploy: the
 * `functions` pattern in vercel.json is validated *before* the build command
 * runs, so the file has to exist in the repository for the deployment to be
 * accepted at all. `npm run test:sync-data` checks the committed copy still
 * matches its source, so the two cannot drift.
 *
 *   npm run build:api          # write api/sync.js
 *   npm run build:api -- --check   # fail if the committed bundle is stale
 */

import { build } from 'esbuild';
import { mkdir, readFile } from 'node:fs/promises';

const OUT = 'api/sync.js';
const LIVE_OUT = 'api/live-matchups.js';
const check = process.argv.includes('--check');

await mkdir('api', { recursive: true });

export const BUILD_OPTIONS = {
  entryPoints: ['lib/api/syncRoute.ts'],
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  sourcemap: false,
  banner: {
    js: '// Generated by scripts/build-api.mjs from lib/api/syncRoute.ts — do not edit.'
  }
};

if (check) {
  const fresh = await build({ ...BUILD_OPTIONS, outfile: undefined, write: false });
  const built = fresh.outputFiles[0].text;
  const committed = await readFile(OUT, 'utf8').catch(() => '');
  if (built !== committed) {
    process.stderr.write(`${OUT} is stale — run \`npm run build:api\`\n`);
    process.exit(1);
  }
  const live = await build({ ...BUILD_OPTIONS, entryPoints: ['lib/api/liveMatchupEntry.ts'],
    banner: { js: '// Generated by scripts/build-api.mjs from lib/api/liveMatchupEntry.ts — do not edit.' },
    outfile: undefined, write: false });
  const liveCommitted = await readFile(LIVE_OUT, 'utf8').catch(() => '');
  if (live.outputFiles[0].text !== liveCommitted) {
    process.stderr.write(`${LIVE_OUT} is stale — run \`npm run build:api\`\n`);
    process.exit(1);
  }
  process.stdout.write(`${OUT} is up to date\n`);
} else {
  const result = await build({ ...BUILD_OPTIONS, outfile: OUT, metafile: true, logLevel: 'info' });
  const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
  process.stdout.write(`built ${OUT} (${(bytes / 1024).toFixed(1)} kB)\n`);
  await build({ ...BUILD_OPTIONS, entryPoints: ['lib/api/liveMatchupEntry.ts'], outfile: LIVE_OUT,
    banner: { js: '// Generated by scripts/build-api.mjs from lib/api/liveMatchupEntry.ts — do not edit.' } });
}
