/**
 * scripts/build-api.mjs
 * -----------------------------------------------------------------------------
 * Bundles the Vercel Function: lib/api/syncRoute.ts -> api/sync.js.
 *
 * Why a build step for this one file, in a project that otherwise has none:
 * Vercel's TypeScript step compiles the function entrypoint but leaves its
 * `.ts` import specifiers alone and does not trace them, so a deployed
 * `api/sync.ts` dies at runtime with
 *
 *   ERR_MODULE_NOT_FOUND: Cannot find module '/var/task/lib/services/sportsData.ts'
 *
 * esbuild resolves those specifiers and inlines the service into one ESM file,
 * so the function carries no dependency on runtime type stripping or on module
 * tracing. Nothing else in the project needs building: the browser app is
 * static, and the CLI and tests import the `.ts` modules directly.
 *
 *   npm run build:api          # or `npm run build`, which Vercel runs for us
 */

import { build } from 'esbuild';
import { mkdir } from 'node:fs/promises';

const OUT = 'api/sync.js';

await mkdir('api', { recursive: true });

const result = await build({
  entryPoints: ['lib/api/syncRoute.ts'],
  outfile: OUT,
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'esm',
  sourcemap: false,
  logLevel: 'info',
  metafile: true,
  banner: {
    js: '// Generated by scripts/build-api.mjs from lib/api/syncRoute.ts — do not edit.'
  }
});

const bytes = Object.values(result.metafile.outputs)[0]?.bytes ?? 0;
process.stdout.write(`built ${OUT} (${(bytes / 1024).toFixed(1)} kB)\n`);
