// Generated by scripts/build-api.mjs from lib/api/syncRoute.ts — do not edit.

// lib/services/env.ts
var DEFAULT_SUPABASE_URL = "https://opfrwtjqjciqpmajeqlr.supabase.co";
var DEFAULT_ENDPOINTS = {
  teams: "/getNFLTeams",
  playerList: "/getNFLPlayerList",
  roster: "/getNFLTeamRoster",
  projections: "/getNFLProjections",
  games: "/getNFLGamesForWeek",
  boxScore: "/getNFLBoxScore"
};
var SEASON_TYPES = ["pre", "reg", "post"];
var SCORING_FORMATS = ["standard", "half_ppr", "ppr", "superflex", "custom"];
function str(source, key, fallback = "") {
  const value = source[key];
  return value === void 0 || value === "" ? fallback : value.trim();
}
function int(source, key, fallback) {
  const raw = str(source, key);
  if (!raw) return fallback;
  const parsed = Number.parseInt(raw, 10);
  if (!Number.isFinite(parsed)) {
    throw new TypeError(`${key} must be an integer, got "${raw}"`);
  }
  return parsed;
}
function bool(source, key, fallback = false) {
  const raw = str(source, key).toLowerCase();
  if (!raw) return fallback;
  return raw === "1" || raw === "true" || raw === "yes" || raw === "on";
}
function currentSeason(now = /* @__PURE__ */ new Date()) {
  const year = now.getUTCFullYear();
  return now.getUTCMonth() >= 2 ? year : year - 1;
}
function seasonKickoff(season) {
  const september = new Date(Date.UTC(season, 8, 1));
  const firstMonday = 1 + (8 - september.getUTCDay()) % 7;
  return new Date(Date.UTC(season, 8, firstMonday + 3));
}
function currentNflWeek(now = /* @__PURE__ */ new Date(), season) {
  const kickoff = seasonKickoff(season ?? currentSeason(now));
  const days = Math.floor((now.getTime() - kickoff.getTime()) / 864e5);
  if (days < 0) return 1;
  return Math.min(18, Math.floor(days / 7) + 1);
}
function weekFocus(now = /* @__PURE__ */ new Date(), season) {
  const resolved = season ?? currentSeason(now);
  const week = currentNflWeek(now, resolved);
  const days = Math.floor((now.getTime() - seasonKickoff(resolved).getTime()) / 864e5);
  const dayInWeek = days < 0 ? 0 : days % 7;
  const weekComplete = days >= 0 && dayInWeek >= 5;
  return {
    week,
    weekComplete,
    completed: weekComplete ? week : week > 1 ? week - 1 : null,
    upcoming: weekComplete ? Math.min(18, week + 1) : week
  };
}
function oneOf(value, allowed, key, fallback) {
  if (!value) return fallback;
  if (!allowed.includes(value)) {
    throw new TypeError(`${key} must be one of ${allowed.join(", ")} \u2014 got "${value}"`);
  }
  return value;
}
function endpointOverrides(source) {
  const endpoints = { ...DEFAULT_ENDPOINTS };
  for (const key of Object.keys(endpoints)) {
    const envKey = `SPORTS_DATA_ENDPOINT_${key.replace(/[A-Z]/g, (c) => `_${c}`).toUpperCase()}`;
    const override = str(source, envKey);
    if (override) endpoints[key] = override;
  }
  return endpoints;
}
function readEnv(source = process.env, now = /* @__PURE__ */ new Date()) {
  const apiHost = str(source, "SPORTS_DATA_API_HOST");
  const baseUrl = str(source, "SPORTS_DATA_BASE_URL", apiHost ? `https://${apiHost}` : "");
  const secretKey = str(source, "SUPABASE_SERVICE_ROLE_KEY") || str(source, "SUPABASE_SECRET_KEY") || str(source, "SUPABASE_KEY");
  const publishableKey = str(source, "SUPABASE_PUBLISHABLE_KEY");
  return {
    provider: str(source, "SPORTS_DATA_PROVIDER", "tank01").toLowerCase(),
    apiKey: str(source, "SPORTS_DATA_API_KEY"),
    apiHost,
    baseUrl: baseUrl.replace(/\/+$/, ""),
    apiKeyHeader: str(source, "SPORTS_DATA_API_KEY_HEADER", "x-rapidapi-key"),
    apiHostHeader: str(source, "SPORTS_DATA_API_HOST_HEADER", "x-rapidapi-host"),
    season: int(source, "SPORTS_DATA_SEASON", currentSeason(now)),
    seasonType: oneOf(str(source, "SPORTS_DATA_SEASON_TYPE"), SEASON_TYPES, "SPORTS_DATA_SEASON_TYPE", "reg"),
    scoringFormat: oneOf(
      str(source, "SPORTS_DATA_SCORING"),
      SCORING_FORMATS,
      "SPORTS_DATA_SCORING",
      "ppr"
    ),
    weekOverride: str(source, "SPORTS_DATA_WEEK") ? int(source, "SPORTS_DATA_WEEK", 0) : null,
    scheduleWeeks: int(source, "SPORTS_DATA_SCHEDULE_WEEKS", 18),
    batchSize: Math.max(1, int(source, "SPORTS_DATA_BATCH_SIZE", 120)),
    timeoutMs: int(source, "SPORTS_DATA_TIMEOUT_MS", 15e3),
    maxRetries: Math.max(0, int(source, "SPORTS_DATA_MAX_RETRIES", 3)),
    retryBaseMs: Math.max(0, int(source, "SPORTS_DATA_RETRY_BASE_MS", 500)),
    rateLimitMs: Math.max(0, int(source, "SPORTS_DATA_RATE_LIMIT_MS", 0)),
    maxGamesPerWeek: Math.max(1, int(source, "SPORTS_DATA_MAX_GAMES_PER_WEEK", 16)),
    fixtureDir: str(source, "SPORTS_DATA_FIXTURE_DIR", "lib/fixtures/tank01"),
    dryRun: bool(source, "SPORTS_DATA_DRY_RUN"),
    logLevel: str(source, "SPORTS_DATA_LOG_LEVEL", str(source, "LOG_LEVEL", "info")).toLowerCase(),
    logJson: bool(source, "SPORTS_DATA_LOG_JSON"),
    supabaseUrl: str(source, "SUPABASE_URL", DEFAULT_SUPABASE_URL).replace(/\/+$/, ""),
    supabaseKey: secretKey || publishableKey,
    supabaseKeySource: secretKey ? "secret" : publishableKey ? "publishable" : "none",
    endpoints: endpointOverrides(source)
  };
}

// lib/services/logger.ts
var ORDER = { debug: 10, info: 20, warn: 30, error: 40, silent: 99 };
function normalizeLevel(level) {
  const candidate = (level || "info").toLowerCase();
  return candidate in ORDER ? candidate : "info";
}
function format(value) {
  if (value instanceof Error) return value.message;
  if (typeof value === "string") return /[\s"]/.test(value) ? JSON.stringify(value) : value;
  if (value === null || value === void 0) return String(value);
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}
function createLogger(options = {}) {
  const level = normalizeLevel(options.level);
  const bindings = options.bindings ?? {};
  const write = options.write ?? ((line) => process.stdout.write(`${line}
`));
  const json2 = options.json ?? false;
  function emit(at, message, fields = {}) {
    if (ORDER[at] < ORDER[level]) return;
    const merged = { ...bindings, ...fields };
    if (json2) {
      write(JSON.stringify({ ts: (/* @__PURE__ */ new Date()).toISOString(), level: at, msg: message, ...merged }));
      return;
    }
    const tail = Object.entries(merged).map(([key, value]) => `${key}=${format(value)}`).join(" ");
    const stamp = (/* @__PURE__ */ new Date()).toISOString().slice(11, 23);
    write(`${stamp} ${at.toUpperCase().padEnd(5)} ${message}${tail ? ` ${tail}` : ""}`);
  }
  return {
    level,
    debug: (message, fields) => emit("debug", message, fields),
    info: (message, fields) => emit("info", message, fields),
    warn: (message, fields) => emit("warn", message, fields),
    error: (message, fields) => emit("error", message, fields),
    child: (extra) => createLogger({ ...options, level, bindings: { ...bindings, ...extra } })
  };
}
var silentLogger = createLogger({ level: "silent", write: () => {
} });

// lib/services/normalize.ts
function num(value, fallback = 0) {
  if (typeof value === "number") return Number.isFinite(value) ? value : fallback;
  if (typeof value === "string") {
    const cleaned = value.replace(/,/g, "").trim();
    if (!cleaned) return fallback;
    const parsed = Number.parseFloat(cleaned);
    return Number.isFinite(parsed) ? parsed : fallback;
  }
  return fallback;
}
function optionalNum(value) {
  if (value === void 0 || value === null || value === "") return null;
  const parsed = num(value, Number.NaN);
  return Number.isFinite(parsed) ? parsed : null;
}
function text(value) {
  if (typeof value === "string") {
    const trimmed = value.trim();
    return trimmed === "" ? null : trimmed;
  }
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  return null;
}
var POSITION_ALIASES = {
  QB: "QB",
  RB: "RB",
  FB: "RB",
  "RB/WR": "RB",
  HB: "RB",
  WR: "WR",
  "WR/RB": "WR",
  TE: "TE",
  K: "K",
  PK: "K",
  DST: "DST",
  DEF: "DST",
  "D/ST": "DST",
  DEFENSE: "DST"
};
function fantasyPosition(value) {
  const raw = text(value);
  if (!raw) return null;
  return POSITION_ALIASES[raw.toUpperCase()] ?? null;
}
function teamAbbr(value, fallback = "FA") {
  const raw = text(value);
  if (!raw) return fallback;
  return raw.toUpperCase();
}
var GAME_STATUS_ALIASES = [
  [/^(completed|final|closed|f\/ot)/i, "final"],
  [/(live|in\s*progress|progress|halftime|q[1-4])/i, "in_progress"],
  [/postponed|suspended|delayed/i, "postponed"],
  [/cancel/i, "canceled"],
  [/scheduled|not\s*started|pre[-\s]?game/i, "scheduled"]
];
function gameStatus(value, fallback = "scheduled") {
  const raw = text(value);
  if (!raw) return fallback;
  for (const [pattern, status] of GAME_STATUS_ALIASES) {
    if (pattern.test(raw)) return status;
  }
  return fallback;
}
function kickoffIso(input) {
  const epoch = optionalNum(input.epoch);
  if (epoch && epoch > 1e9 && epoch < 1e10) {
    return new Date(Math.round(epoch * 1e3)).toISOString();
  }
  const iso = text(input.iso);
  if (iso) {
    const parsed = new Date(iso);
    if (!Number.isNaN(parsed.getTime())) return parsed.toISOString();
  }
  const date = text(input.date);
  if (!date) return null;
  const compact = /^(\d{4})(\d{2})(\d{2})$/.exec(date);
  const dashed = /^(\d{4})-(\d{2})-(\d{2})$/.exec(date);
  const parts = compact ?? dashed;
  if (!parts) return null;
  const [, year, month, day] = parts;
  let hour = 13;
  let minute = 0;
  const time = text(input.time);
  const clock = time ? /^(\d{1,2}):(\d{2})\s*([ap])?/i.exec(time) : null;
  if (clock) {
    hour = Number.parseInt(clock[1], 10);
    minute = Number.parseInt(clock[2], 10);
    const meridiem = clock[3]?.toLowerCase();
    if (meridiem === "p" && hour < 12) hour += 12;
    if (meridiem === "a" && hour === 12) hour = 0;
  }
  const monthNum = Number.parseInt(month, 10);
  const dayNum = Number.parseInt(day, 10);
  const easternOffset = monthNum > 11 || monthNum < 3 || monthNum === 11 && dayNum > 7 ? 5 : 4;
  const utc = Date.UTC(
    Number.parseInt(year, 10),
    monthNum - 1,
    dayNum,
    hour + easternOffset,
    minute
  );
  return new Date(utc).toISOString();
}
function flattenStats(input, prefix = "", options = {}) {
  const out = {};
  if (!input || typeof input !== "object" || Array.isArray(input)) return out;
  for (const [key, value] of Object.entries(input)) {
    if (!prefix && options.exclude?.has(key)) continue;
    const path = prefix ? `${prefix}.${key}` : key;
    if (value && typeof value === "object" && !Array.isArray(value)) {
      Object.assign(out, flattenStats(value, path.toLowerCase(), options));
      continue;
    }
    const parsed = optionalNum(value);
    if (parsed !== null) out[path] = parsed;
  }
  return out;
}
function assertWeek(week, label = "week") {
  const parsed = optionalNum(week);
  if (parsed === null || !Number.isInteger(parsed) || parsed < 1 || parsed > 22) {
    throw new TypeError(`${label} must be an integer between 1 and 22, got ${String(week)}`);
  }
  return parsed;
}
function chunk(rows, size) {
  if (size <= 0) throw new TypeError(`chunk size must be positive, got ${size}`);
  const out = [];
  for (let i = 0; i < rows.length; i += size) out.push(rows.slice(i, i + size));
  return out;
}

// lib/services/httpClient.ts
var HttpError = class extends Error {
  status;
  url;
  body;
  constructor(message, status, url, body = "") {
    super(message);
    this.name = "HttpError";
    this.status = status;
    this.url = url;
    this.body = body;
  }
};
var RETRYABLE = /* @__PURE__ */ new Set([408, 425, 429, 500, 502, 503, 504, 522, 524]);
function defaultSleep(ms) {
  return new Promise((resolve2) => {
    setTimeout(resolve2, ms);
  });
}
function buildUrl(baseUrl, path, query = {}) {
  const base = baseUrl.replace(/\/+$/, "");
  const suffix = path.startsWith("http") ? path : `${base}${path.startsWith("/") ? "" : "/"}${path}`;
  const url = new URL(suffix);
  for (const [key, value] of Object.entries(query)) {
    if (value === void 0 || value === null || value === "") continue;
    url.searchParams.set(key, String(value));
  }
  return url.toString();
}
function createHttpClient(baseUrl, options = {}) {
  const doFetch = options.fetch ?? globalThis.fetch;
  const logger = options.logger ?? silentLogger;
  const sleep = options.sleep ?? defaultSleep;
  const timeoutMs = options.timeoutMs ?? 15e3;
  const maxRetries = options.maxRetries ?? 3;
  const retryBaseMs = options.retryBaseMs ?? 500;
  const rateLimitMs = options.rateLimitMs ?? 0;
  if (!doFetch) {
    throw new Error("No fetch implementation available \u2014 pass options.fetch.");
  }
  const fetchJson = doFetch;
  let calls = 0;
  let lastCallAt = 0;
  async function throttle() {
    if (!rateLimitMs) return;
    const wait = rateLimitMs - (Date.now() - lastCallAt);
    if (wait > 0) await sleep(wait);
  }
  async function getJson(path, query = {}) {
    const url = buildUrl(baseUrl, path, query);
    let attempt = 0;
    for (; ; ) {
      await throttle();
      const startedAt = Date.now();
      calls += 1;
      lastCallAt = startedAt;
      try {
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), timeoutMs);
        let response;
        try {
          response = await fetchJson(url, {
            method: "GET",
            headers: { accept: "application/json", ...options.headers ?? {} },
            signal: controller.signal
          });
        } finally {
          clearTimeout(timer);
        }
        const durationMs = Date.now() - startedAt;
        if (!response.ok) {
          const body = (await response.text().catch(() => "")).slice(0, 500);
          const error = new HttpError(
            `GET ${path} failed (${response.status})${body ? `: ${body}` : ""}`,
            response.status,
            url,
            body
          );
          if (RETRYABLE.has(response.status) && attempt < maxRetries) {
            const retryAfter = Number.parseInt(response.headers.get("retry-after") ?? "", 10);
            const delay = Number.isFinite(retryAfter) ? retryAfter * 1e3 : retryBaseMs * 2 ** attempt;
            logger.warn("provider request failed, retrying", {
              path,
              status: response.status,
              attempt: attempt + 1,
              delay_ms: delay
            });
            attempt += 1;
            await sleep(delay);
            continue;
          }
          throw error;
        }
        const json2 = await response.json();
        logger.debug("provider request ok", { path, status: response.status, ms: durationMs });
        return { url, status: response.status, json: json2, durationMs };
      } catch (error) {
        const isHttp = error instanceof HttpError;
        if (isHttp || attempt >= maxRetries) throw error;
        const delay = retryBaseMs * 2 ** attempt;
        logger.warn("provider request errored, retrying", {
          path,
          attempt: attempt + 1,
          delay_ms: delay,
          error: error.message
        });
        attempt += 1;
        await sleep(delay);
      }
    }
  }
  return {
    getJson,
    get calls() {
      return calls;
    }
  };
}

// lib/services/providers/tank01.ts
var TANK01_PROVIDER_NAME = "tank01";
var SCORING_PARAMS = {
  standard: { pointsPerReception: 0 },
  half_ppr: { pointsPerReception: 0.5 },
  ppr: { pointsPerReception: 1 },
  superflex: { pointsPerReception: 1 },
  custom: {}
};
var BASE_SCORING = {
  passYards: 0.04,
  passTD: 4,
  passInterceptions: -2,
  passCompletions: 0,
  passAttempts: 0,
  carries: 0,
  rushYards: 0.1,
  rushTD: 6,
  fumbles: -2,
  receivingYards: 0.1,
  receivingTD: 6,
  targets: 0,
  twoPointConversions: 2,
  fgMade: 3,
  fgMissed: -1,
  xpMade: 1,
  xpMissed: -1,
  idwTackleSolo: 0,
  defTD: 6,
  defSack: 1,
  defInt: 2,
  defFumblesRecovered: 2,
  defSafety: 2
};
function scoringQuery(format2) {
  return { ...BASE_SCORING, ...SCORING_PARAMS[format2] };
}
var STAT_EXCLUDE = /* @__PURE__ */ new Set([
  "__key",
  "playerID",
  "teamID",
  "teamAbv",
  "team",
  "pos",
  "position",
  "longName",
  "espnName",
  "cbsShortName",
  "opponent",
  "gameID",
  "gameWeek",
  "season",
  "week",
  "jerseyNum",
  "fantasyPoints",
  "fantasyPointsDefault",
  "snapCounts"
]);
var statsOf = (entry) => flattenStats(entry, "", { exclude: STAT_EXCLUDE });
function fantasyPointsOf(entry, format2) {
  const direct = optionalNum(entry.fantasyPoints);
  if (direct !== null) return direct;
  const fallback = entry.fantasyPointsDefault;
  if (fallback && typeof fallback === "object" && !Array.isArray(fallback)) {
    const table = fallback;
    const key = format2 === "standard" ? "standard" : format2 === "half_ppr" ? "halfPPR" : "PPR";
    return num(table[key] ?? table.PPR ?? Object.values(table)[0]);
  }
  return num(fallback);
}
var DST_WEIGHTS = {
  sack: 1,
  interception: 2,
  fumbleRecovery: 2,
  touchdown: 6,
  safety: 2,
  blockedKick: 2
};
function pointsAllowedBonus(pointsAllowed) {
  if (pointsAllowed <= 0) return 10;
  if (pointsAllowed <= 6) return 7;
  if (pointsAllowed <= 13) return 4;
  if (pointsAllowed <= 20) return 1;
  if (pointsAllowed <= 27) return 0;
  if (pointsAllowed <= 34) return -1;
  return -4;
}
function firstNum(entry, keys) {
  for (const key of keys) {
    const value = optionalNum(entry[key]);
    if (value !== null) return value;
  }
  return 0;
}
function defenseFantasyPoints(entry) {
  const present = [
    "sacks",
    "defSack",
    "defensiveInterceptions",
    "interceptions",
    "defInt",
    "fumblesRecovered",
    "fumbleRecoveries",
    "defTD",
    "ptsAllowed",
    "ptsAgainst"
  ].some((key) => optionalNum(entry[key]) !== null);
  if (!present) return null;
  const total = firstNum(entry, ["sacks", "defSack"]) * DST_WEIGHTS.sack + firstNum(entry, ["defensiveInterceptions", "interceptions", "defInt"]) * DST_WEIGHTS.interception + firstNum(entry, ["fumblesRecovered", "fumbleRecoveries", "defFumblesRecovered"]) * DST_WEIGHTS.fumbleRecovery + (firstNum(entry, ["defTD"]) + firstNum(entry, ["returnTD"])) * DST_WEIGHTS.touchdown + firstNum(entry, ["safeties", "defSafety"]) * DST_WEIGHTS.safety + firstNum(entry, ["blockKick", "blockedKick"]) * DST_WEIGHTS.blockedKick + pointsAllowedBonus(firstNum(entry, ["ptsAllowed", "ptsAgainst"]));
  return Math.round(total * 100) / 100;
}
function defenseTeamAbbr(entry) {
  const explicit = text(entry.teamAbv) ?? text(entry.team);
  if (explicit && !/^\d+$/.test(explicit)) return teamAbbr(explicit, explicit);
  const key = text(entry.__key);
  if (key && !/^\d+$/.test(key) && !/^(home|away)$/i.test(key)) return teamAbbr(key, key);
  return null;
}
function unwrap(payload) {
  if (payload && typeof payload === "object" && !Array.isArray(payload) && "body" in payload) {
    return payload.body;
  }
  return payload;
}
function asRecords(body) {
  if (Array.isArray(body)) return body.filter((row) => !!row && typeof row === "object");
  if (body && typeof body === "object") {
    return Object.entries(body).filter(([, value]) => !!value && typeof value === "object" && !Array.isArray(value)).map(([key, value]) => ({ __key: key, ...value }));
  }
  return [];
}
function byeWeek(value, season) {
  if (!value || typeof value !== "object") return null;
  const table = value;
  const candidate = table[String(season)] ?? Object.values(table)[0];
  if (Array.isArray(candidate)) return optionalNum(candidate[0]);
  return optionalNum(candidate);
}
function teamsFromGameId(gameId) {
  if (!gameId) return { away: null, home: null };
  const match = /_([A-Z]{2,4})@([A-Z]{2,4})$/.exec(gameId.toUpperCase());
  return match ? { away: match[1], home: match[2] } : { away: null, home: null };
}
function createTank01Provider(options) {
  const { env } = options;
  const logger = options.logger ?? silentLogger;
  const name = options.name ?? TANK01_PROVIDER_NAME;
  const endpoints = env.endpoints;
  const http = options.http ?? createHttpClient(env.baseUrl, {
    headers: {
      [env.apiKeyHeader]: env.apiKey,
      [env.apiHostHeader]: env.apiHost
    },
    timeoutMs: env.timeoutMs,
    maxRetries: env.maxRetries,
    retryBaseMs: env.retryBaseMs,
    rateLimitMs: env.rateLimitMs,
    logger
  });
  function requireCredentials() {
    if (options.http) return;
    const missing = [];
    if (!env.apiKey) missing.push("SPORTS_DATA_API_KEY");
    if (!env.apiHost && !env.baseUrl) missing.push("SPORTS_DATA_API_HOST");
    if (missing.length) {
      throw new Error(
        `${name}: missing ${missing.join(" and ")} \u2014 set them, or run with SPORTS_DATA_PROVIDER=fixture.`
      );
    }
  }
  async function get(endpoint, query = {}) {
    requireCredentials();
    const path = endpoints[endpoint];
    if (!path) throw new Error(`${name}: no endpoint configured for "${endpoint}"`);
    const response = await http.getJson(path, query);
    return unwrap(response.json);
  }
  function describe() {
    return {
      name,
      host: env.apiHost || null,
      endpoints: { ...endpoints },
      configured: Boolean(options.http) || Boolean(env.apiKey && (env.apiHost || env.baseUrl)),
      notes: options.http ? ["transport injected \u2014 no network calls"] : void 0
    };
  }
  async function fetchTeams(context) {
    const body = await get("teams", {
      rosters: "false",
      schedules: "false",
      topPerformers: "false",
      teamStats: "false"
    });
    return asRecords(body).map((row) => {
      const externalId = text(row.teamID) ?? text(row.__key);
      const abbr = text(row.teamAbv) ?? text(row.abbreviation);
      if (!externalId || !abbr) return null;
      return {
        external_id: externalId,
        abbr: teamAbbr(abbr, abbr),
        city: text(row.teamCity),
        name: text(row.teamName),
        conference: text(row.conference) ?? text(row.conferenceAbv),
        division: text(row.division),
        bye_week: byeWeek(row.byeWeeks, context.season),
        logo_url: text(row.espnLogo1) ?? text(row.nflComLogo1),
        raw: row
      };
    }).filter((row) => row !== null);
  }
  function mapRosterPlayer(row, fallbackTeam, fallbackTeamId, bye) {
    const externalId = text(row.playerID) ?? text(row.__key);
    const name2 = text(row.longName) ?? text(row.espnName) ?? text(row.cbsShortName);
    const position = fantasyPosition(row.pos ?? row.position);
    if (!externalId || !name2 || !position) return null;
    const injury = row.injury && typeof row.injury === "object" ? row.injury : {};
    return {
      external_id: externalId,
      name: name2,
      position,
      team: teamAbbr(row.team ?? fallbackTeam),
      nfl_team_external_id: text(row.teamID) ?? fallbackTeamId,
      jersey: text(row.jerseyNum),
      status: text(injury.designation) ?? text(row.status) ?? "Active",
      injury,
      bye_week: bye,
      age: optionalNum(row.age),
      experience: text(row.exp),
      college: text(row.school) ?? text(row.college),
      adp: null,
      stats: {},
      raw: row
    };
  }
  async function fetchPlayers(context) {
    const body = await get("teams", {
      rosters: "true",
      schedules: "false",
      topPerformers: "false",
      teamStats: "false"
    });
    const teams = asRecords(body);
    const players = [];
    const seen = /* @__PURE__ */ new Set();
    for (const team of teams) {
      const abbr = text(team.teamAbv);
      const teamId = text(team.teamID);
      const bye = byeWeek(team.byeWeeks, context.season);
      const roster = team.Roster ?? team.roster;
      for (const entry of asRecords(roster)) {
        const player = mapRosterPlayer(entry, abbr, teamId, bye);
        if (!player || seen.has(player.external_id)) continue;
        seen.add(player.external_id);
        players.push(player);
      }
    }
    if (players.length > 0) {
      logger.debug("mapped rosters", { teams: teams.length, players: players.length });
      return players;
    }
    logger.warn("no rosters in teams payload \u2014 falling back to the flat player list");
    const list = await get("playerList");
    for (const entry of asRecords(list)) {
      const player = mapRosterPlayer(entry, null, null, null);
      if (!player || seen.has(player.external_id)) continue;
      seen.add(player.external_id);
      players.push(player);
    }
    return players;
  }
  async function fetchProjections(context) {
    const week = assertWeek(context.week, "week");
    const body = await get("projections", {
      week,
      archiveSeason: context.season,
      ...scoringQuery(context.scoringFormat)
    });
    const envelope = body ?? {};
    const source = endpoints.projections;
    const rows = [];
    const base = {
      season: context.season,
      week,
      season_type: context.seasonType,
      scoring_format: context.scoringFormat,
      source
    };
    for (const entry of asRecords(envelope.playerProjections ?? envelope)) {
      const externalId = text(entry.playerID) ?? text(entry.__key);
      if (!externalId) continue;
      const stats = statsOf(entry);
      rows.push({
        ...base,
        external_player_id: externalId,
        player_id: `${name}-${externalId}`,
        name: text(entry.longName) ?? text(entry.espnName),
        position: text(entry.pos) ?? text(entry.position),
        team: text(entry.team) ? teamAbbr(entry.team) : null,
        // The live projections feed carries no opponent; fsnv2_sync_projections
        // derives it from fsnv2.nfl_matchups on the way in (migration 0005).
        opponent: text(entry.opponent) ? teamAbbr(entry.opponent) : null,
        fantasy_points: fantasyPointsOf(entry, context.scoringFormat),
        stats,
        raw: entry
      });
    }
    for (const entry of asRecords(envelope.teamDefenseProjections)) {
      const abbr = defenseTeamAbbr(entry);
      if (!abbr) {
        logger.warn("skipping a team defense projection with no resolvable team", {
          key: text(entry.__key)
        });
        continue;
      }
      const stats = statsOf(entry);
      const provided = fantasyPointsOf(entry, context.scoringFormat);
      rows.push({
        ...base,
        external_player_id: `DST-${abbr}`,
        player_id: null,
        name: `${abbr} D/ST`,
        position: "DST",
        team: abbr,
        opponent: text(entry.opponent) ? teamAbbr(entry.opponent) : null,
        fantasy_points: provided || (defenseFantasyPoints(entry) ?? 0),
        stats,
        raw: entry
      });
    }
    return rows;
  }
  function mapGame(row, context, week) {
    const externalId = text(row.gameID) ?? text(row.__key);
    if (!externalId) return null;
    const fromId = teamsFromGameId(externalId);
    const home = text(row.home) ?? text(row.homeTeam) ?? fromId.home;
    const away = text(row.away) ?? text(row.awayTeam) ?? fromId.away;
    if (!home || !away) return null;
    const status = gameStatus(row.gameStatus ?? row.status);
    return {
      external_id: externalId,
      season: optionalNum(row.season) ?? context.season,
      week: optionalNum(row.gameWeek ? String(row.gameWeek).replace(/\D+/g, "") : null) ?? week,
      season_type: context.seasonType,
      home_team: teamAbbr(home, home),
      away_team: teamAbbr(away, away),
      home_score: optionalNum(row.homePts),
      away_score: optionalNum(row.awayPts),
      kickoff: kickoffIso({
        epoch: row.gameTime_epoch,
        iso: row.gameTimeISO,
        date: row.gameDate,
        time: row.gameTime
      }),
      status,
      venue: text(row.venue) ?? text(row.stadium),
      neutral_site: row.neutralSite === true || text(row.neutralSite)?.toLowerCase() === "true",
      source: endpoints.games,
      raw: row
    };
  }
  async function fetchWeekGames(context, week) {
    const body = await get("games", {
      week,
      season: context.season,
      seasonType: context.seasonType
    });
    return asRecords(body).map((row) => mapGame(row, context, week)).filter((row) => row !== null);
  }
  async function fetchSchedules(context) {
    const weeks = context.weeks && context.weeks.length > 0 ? context.weeks.map((week) => assertWeek(week, "week")) : context.week ? [assertWeek(context.week, "week")] : Array.from({ length: env.scheduleWeeks }, (_, index) => index + 1);
    const games = [];
    const seen = /* @__PURE__ */ new Set();
    for (const week of weeks) {
      const weekGames = await fetchWeekGames(context, week);
      for (const game of weekGames) {
        if (seen.has(game.external_id)) continue;
        seen.add(game.external_id);
        games.push(game);
      }
      logger.debug("mapped week schedule", { week, games: weekGames.length });
    }
    return games;
  }
  function mapBoxScorePlayer(entry, context, week, gameId, teams) {
    const externalId = text(entry.playerID) ?? text(entry.__key);
    if (!externalId) return null;
    const team = text(entry.teamAbv) ?? text(entry.team);
    const opponent = team && teams.home && teams.away ? teamAbbr(team) === teamAbbr(teams.home) ? teamAbbr(teams.away) : teamAbbr(teams.home) : null;
    const snapCounts = entry.snapCounts && typeof entry.snapCounts === "object" ? entry.snapCounts : {};
    const stats = statsOf(entry);
    return {
      external_player_id: externalId,
      player_id: `${name}-${externalId}`,
      season: context.season,
      week,
      season_type: context.seasonType,
      game_external_id: gameId,
      name: text(entry.longName) ?? text(entry.espnName),
      // Box-score entries carry no position; fsnv2_sync_weekly_stats fills it
      // from the synced player pool on the way in (migration 0005).
      position: text(entry.pos) ?? text(entry.position),
      team: team ? teamAbbr(team) : null,
      opponent,
      fantasy_points: fantasyPointsOf(entry, context.scoringFormat),
      stats,
      snap_counts: flattenStats(snapCounts),
      source: endpoints.boxScore,
      raw: entry
    };
  }
  async function fetchBoxScores(context) {
    const week = assertWeek(context.week, "week");
    const games = await fetchWeekGames(context, week);
    const playable = games.filter((game) => game.status !== "canceled" && game.status !== "postponed").slice(0, env.maxGamesPerWeek);
    const rows = [];
    const seen = /* @__PURE__ */ new Set();
    for (const game of playable) {
      const body = await get("boxScore", {
        gameID: game.external_id,
        playByPlay: "false",
        fantasyPoints: "true",
        ...scoringQuery(context.scoringFormat)
      });
      const envelope = body ?? {};
      const teams = { home: game.home_team, away: game.away_team };
      for (const entry of asRecords(envelope.playerStats)) {
        const row = mapBoxScorePlayer(entry, context, week, game.external_id, teams);
        if (!row || seen.has(row.external_player_id)) continue;
        seen.add(row.external_player_id);
        rows.push(row);
      }
      for (const entry of asRecords(envelope.DST)) {
        const abbr = defenseTeamAbbr(entry);
        if (!abbr) continue;
        const externalId = `DST-${abbr}`;
        if (seen.has(externalId)) continue;
        seen.add(externalId);
        const stats = statsOf(entry);
        const provided = fantasyPointsOf(entry, context.scoringFormat);
        rows.push({
          external_player_id: externalId,
          player_id: null,
          season: context.season,
          week,
          season_type: context.seasonType,
          game_external_id: game.external_id,
          name: `${abbr} D/ST`,
          position: "DST",
          team: abbr,
          opponent: abbr === teamAbbr(game.home_team) ? game.away_team : game.home_team,
          fantasy_points: provided || (defenseFantasyPoints(entry) ?? 0),
          stats,
          snap_counts: {},
          source: endpoints.boxScore,
          raw: entry
        });
      }
      logger.debug("mapped box score", { game: game.external_id, rows: rows.length });
    }
    return rows;
  }
  return {
    name,
    describe,
    fetchTeams,
    fetchPlayers,
    fetchProjections,
    fetchBoxScores,
    fetchSchedules
  };
}

// lib/services/providers/fixtureTransport.ts
import { readFileSync } from "node:fs";
import { existsSync } from "node:fs";
import { isAbsolute, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
var REPO_ROOT = resolve(fileURLToPath(new URL("../../..", import.meta.url)));
function candidates(endpoint, url) {
  const names = [`${endpoint}.json`];
  const gameId = url.searchParams.get("gameID");
  if (gameId) names.unshift(`${endpoint}.${gameId}.json`);
  const week = url.searchParams.get("week");
  if (week) names.unshift(`${endpoint}.week${week}.json`);
  if (url.searchParams.get("rosters") === "true") names.unshift(`${endpoint}.rosters.json`);
  return names;
}
function resolveFixtureDir(dir) {
  return isAbsolute(dir) ? dir : join(REPO_ROOT, dir);
}
function createFixtureFetch(options = {}) {
  const dir = resolveFixtureDir(options.dir ?? "lib/fixtures/tank01");
  return async function fixtureFetch(input) {
    const url = new URL(input);
    const endpoint = url.pathname.replace(/^\/+/, "").split("/").pop() ?? "";
    let file = null;
    for (const candidate of candidates(endpoint, url)) {
      const path = join(dir, candidate);
      if (existsSync(path)) {
        file = path;
        break;
      }
    }
    options.onRequest?.({ endpoint, file, url: input });
    if (!file) {
      return new Response(
        JSON.stringify({
          statusCode: 404,
          error: `no fixture for "${endpoint}" in ${dir}`
        }),
        { status: 404, headers: { "content-type": "application/json" } }
      );
    }
    return new Response(readFileSync(file, "utf8"), {
      status: 200,
      headers: { "content-type": "application/json" }
    });
  };
}

// lib/services/providers/index.ts
var registry = /* @__PURE__ */ new Map();
function registerProvider(name, factory) {
  registry.set(name.toLowerCase(), factory);
}
function listProviders() {
  return [...registry.keys()].sort();
}
registerProvider(TANK01_PROVIDER_NAME, ({ env, logger, fetch, http }) => {
  const transport = http ?? (fetch ? createHttpClient(env.baseUrl || "https://sports-data.invalid", {
    fetch,
    headers: { [env.apiKeyHeader]: env.apiKey, [env.apiHostHeader]: env.apiHost },
    timeoutMs: env.timeoutMs,
    maxRetries: env.maxRetries,
    retryBaseMs: env.retryBaseMs,
    logger: logger ?? silentLogger
  }) : void 0);
  return createTank01Provider({ env, logger, http: transport });
});
registerProvider("fixture", ({ env, logger, fetch, http }) => {
  const transport = http ?? createHttpClient("https://fixtures.fsn.local", {
    fetch: fetch ?? createFixtureFetch({ dir: env.fixtureDir }),
    timeoutMs: env.timeoutMs,
    maxRetries: 0,
    logger: logger ?? silentLogger
  });
  return createTank01Provider({ env, logger, http: transport, name: "fixture" });
});
function resolveProvider(deps) {
  const name = (deps.env.provider || TANK01_PROVIDER_NAME).toLowerCase();
  const factory = registry.get(name);
  if (!factory) {
    throw new Error(
      `Unknown SPORTS_DATA_PROVIDER "${name}". Registered providers: ${listProviders().join(", ")}.`
    );
  }
  return factory(deps);
}

// lib/services/syncRepository.ts
var RpcError = class extends Error {
  rpc;
  status;
  body;
  constructor(rpc, status, body) {
    super(`${rpc} failed (${status})${body ? `: ${body}` : ""}`);
    this.name = "RpcError";
    this.rpc = rpc;
    this.status = status;
    this.body = body;
  }
};
var EMPTY = { inserted: 0, updated: 0, skipped: 0, total: 0 };
function addCounts(a, b) {
  return {
    inserted: a.inserted + b.inserted,
    updated: a.updated + b.updated,
    skipped: a.skipped + b.skipped,
    total: a.total + b.total
  };
}
function toCount(rpc, payload, total) {
  if (!payload || typeof payload !== "object") {
    throw new RpcError(rpc, 200, `expected an upsert count object, got ${JSON.stringify(payload)}`);
  }
  const row = payload;
  const read = (key) => {
    const value = row[key];
    const parsed = typeof value === "number" ? value : Number.parseInt(String(value ?? 0), 10);
    return Number.isFinite(parsed) ? parsed : 0;
  };
  return {
    inserted: read("inserted"),
    updated: read("updated"),
    skipped: read("skipped"),
    total: read("total") || total
  };
}
function createSupabaseSyncRepository(options) {
  const logger = options.logger ?? silentLogger;
  const batchSize = Math.max(1, options.batchSize ?? 120);
  const maxRetries = Math.max(0, options.maxRetries ?? 3);
  const retryBaseMs = Math.max(0, options.retryBaseMs ?? 500);
  const timeoutMs = options.timeoutMs ?? 2e4;
  const sleep = options.sleep ?? ((ms) => new Promise((done) => {
    setTimeout(done, ms);
  }));
  const injected = options.rpc;
  const url = (options.url ?? "").replace(/\/+$/, "");
  const key = options.key ?? "";
  const doFetch = options.fetch ?? globalThis.fetch;
  if (!injected && (!url || !key)) {
    throw new Error(
      "Supabase credentials missing: set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (or pass options.rpc)."
    );
  }
  async function postRpc(name, args) {
    if (injected) return injected(name, args);
    if (!doFetch) throw new Error("No fetch implementation available for PostgREST.");
    let attempt = 0;
    for (; ; ) {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), timeoutMs);
      try {
        const response = await doFetch(`${url}/rest/v1/rpc/${name}`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            apikey: key,
            Authorization: `Bearer ${key}`
          },
          body: JSON.stringify(args),
          signal: controller.signal
        });
        if (!response.ok) {
          const body = (await response.text().catch(() => "")).slice(0, 500);
          const retryable = response.status === 429 || response.status >= 500;
          if (retryable && attempt < maxRetries) {
            const delay = retryBaseMs * 2 ** attempt;
            logger.warn("rpc failed, retrying", {
              rpc: name,
              status: response.status,
              attempt: attempt + 1,
              delay_ms: delay
            });
            attempt += 1;
            await sleep(delay);
            continue;
          }
          throw new RpcError(name, response.status, body);
        }
        const raw = await response.text();
        return raw ? JSON.parse(raw) : null;
      } catch (error) {
        if (error instanceof RpcError || attempt >= maxRetries) throw error;
        const delay = retryBaseMs * 2 ** attempt;
        logger.warn("rpc errored, retrying", {
          rpc: name,
          attempt: attempt + 1,
          delay_ms: delay,
          error: error.message
        });
        attempt += 1;
        await sleep(delay);
      } finally {
        clearTimeout(timer);
      }
    }
  }
  async function upsertBatched(rpc, argName, rows) {
    if (rows.length === 0) {
      logger.debug("nothing to upsert", { rpc });
      return { ...EMPTY };
    }
    let totals = { ...EMPTY };
    const batches = chunk(rows, batchSize);
    for (const [index, batch] of batches.entries()) {
      const payload = await postRpc(rpc, {
        p_provider: options.provider,
        [argName]: batch
      });
      const count = toCount(rpc, payload, batch.length);
      totals = addCounts(totals, count);
      logger.debug("batch upserted", {
        rpc,
        batch: `${index + 1}/${batches.length}`,
        ...count
      });
    }
    logger.info("upsert complete", { rpc, ...totals });
    return totals;
  }
  return {
    target: injected ? "injected-rpc" : url,
    upsertTeams: (rows) => upsertBatched("fsnv2_sync_nfl_teams", "p_teams", rows),
    upsertPlayers: (rows) => upsertBatched("fsnv2_sync_players", "p_players", rows),
    upsertProjections: (rows) => upsertBatched("fsnv2_sync_projections", "p_rows", rows),
    upsertWeeklyStats: (rows) => upsertBatched("fsnv2_sync_weekly_stats", "p_rows", rows),
    upsertSchedules: (rows) => upsertBatched("fsnv2_sync_schedules", "p_games", rows),
    async logRun(entry) {
      try {
        const id = await postRpc("fsnv2_log_sync_run", {
          p_task: entry.task,
          p_provider: entry.provider,
          p_status: entry.status,
          p_season: entry.season ?? null,
          p_week: entry.week ?? null,
          p_fetched: entry.fetched ?? 0,
          p_written: entry.written ?? 0,
          p_skipped: entry.skipped ?? 0,
          p_duration_ms: entry.duration_ms ?? null,
          p_error: entry.error ?? null,
          p_detail: entry.detail ?? {}
        });
        return typeof id === "string" ? id : null;
      } catch (error) {
        logger.warn("could not write the sync_runs audit row", {
          task: entry.task,
          error: error.message
        });
        return null;
      }
    },
    status: (limit = 10) => postRpc("fsnv2_sync_status", { p_limit: limit })
  };
}
function createDryRunRepository(logger = silentLogger) {
  const count = (rows) => {
    logger.info("dry run \u2014 not writing", { rows: rows.length });
    return Promise.resolve({ inserted: 0, updated: 0, skipped: rows.length, total: rows.length });
  };
  return {
    target: "dry-run",
    upsertTeams: count,
    upsertPlayers: count,
    upsertProjections: count,
    upsertWeeklyStats: count,
    upsertSchedules: count,
    logRun: () => Promise.resolve(null),
    status: () => Promise.resolve({ dryRun: true })
  };
}

// lib/services/sportsData.ts
function isFullEnv(env) {
  return Boolean(env && "endpoints" in env && "provider" in env && "batchSize" in env);
}
function sumCounts(counts) {
  return counts.reduce(
    (total, count) => ({
      inserted: total.inserted + count.inserted,
      updated: total.updated + count.updated,
      skipped: total.skipped + count.skipped,
      total: total.total + count.total
    }),
    { inserted: 0, updated: 0, skipped: 0, total: 0 }
  );
}
function createSportsDataService(options = {}) {
  const env = isFullEnv(options.env) ? options.env : { ...readEnv(options.envSource), ...options.env ?? {} };
  const logger = options.logger ?? createLogger({
    level: env.logLevel,
    json: env.logJson,
    bindings: { provider: env.provider }
  });
  const provider = options.provider ?? resolveProvider({ env, logger, fetch: options.fetch });
  const now = options.now ?? (() => Date.now());
  let liveRepository = options.repository ?? null;
  const dryRepository = createDryRunRepository(logger);
  function repositoryFor(taskOptions) {
    if (taskOptions?.dryRun || env.dryRun) return dryRepository;
    if (options.repository) return options.repository;
    if (!liveRepository) {
      if (env.supabaseKeySource === "publishable") {
        logger.warn(
          "using a publishable Supabase key \u2014 the sync RPCs are granted to service_role only",
          { url: env.supabaseUrl }
        );
      }
      liveRepository = createSupabaseSyncRepository({
        url: env.supabaseUrl,
        key: env.supabaseKey,
        provider: provider.name,
        batchSize: env.batchSize,
        maxRetries: env.maxRetries,
        retryBaseMs: env.retryBaseMs,
        timeoutMs: env.timeoutMs,
        logger
      });
    }
    return liveRepository;
  }
  function contextFor(taskOptions, week) {
    return {
      season: taskOptions?.season ?? env.season,
      seasonType: taskOptions?.seasonType ?? env.seasonType,
      scoringFormat: taskOptions?.scoringFormat ?? env.scoringFormat,
      week
    };
  }
  async function runTask(task, context, repository, steps) {
    const startedAt = now();
    const log = logger.child({ task, season: context.season, week: context.week ?? null });
    log.info("sync started", { target: repository.target });
    const result = {
      task,
      provider: provider.name,
      ok: true,
      season: context.season,
      week: context.week ?? null,
      fetched: 0,
      written: 0,
      inserted: 0,
      updated: 0,
      skipped: 0,
      batches: 0,
      durationMs: 0,
      errors: [],
      runId: null,
      detail: {}
    };
    try {
      const outcome = await steps();
      const totals = sumCounts(outcome.counts);
      result.fetched = outcome.fetched;
      result.inserted = totals.inserted;
      result.updated = totals.updated;
      result.skipped = totals.skipped;
      result.written = totals.inserted + totals.updated;
      result.batches = outcome.counts.length;
      result.detail = outcome.detail ?? {};
      if (outcome.fetched > 0 && result.written === 0 && !env.dryRun) {
        log.warn("provider returned rows but nothing was written", { fetched: outcome.fetched });
      }
    } catch (error) {
      result.ok = false;
      result.errors.push(error.message);
      log.error("sync failed", { error: error.message });
    }
    result.durationMs = now() - startedAt;
    const status = result.ok ? "success" : result.written > 0 ? "partial" : "error";
    result.runId = await repository.logRun({
      task,
      provider: provider.name,
      status,
      season: context.season,
      week: context.week ?? null,
      fetched: result.fetched,
      written: result.written,
      skipped: result.skipped,
      duration_ms: result.durationMs,
      error: result.errors.join(" | ") || null,
      detail: { ...result.detail, batches: result.batches, target: repository.target }
    });
    if (result.ok) {
      log.info("sync finished", {
        fetched: result.fetched,
        written: result.written,
        inserted: result.inserted,
        updated: result.updated,
        skipped: result.skipped,
        ms: result.durationMs
      });
    }
    return result;
  }
  async function syncPlayersAndRosters(taskOptions = {}) {
    const context = contextFor(taskOptions);
    const repository = repositoryFor(taskOptions);
    return runTask("players_rosters", context, repository, async () => {
      const teams = await provider.fetchTeams(context);
      const teamCounts = await repository.upsertTeams(teams);
      const players = await provider.fetchPlayers(context);
      const playerCounts = await repository.upsertPlayers(players);
      return {
        fetched: teams.length + players.length,
        counts: [teamCounts, playerCounts],
        detail: {
          teams: teams.length,
          teams_written: teamCounts.inserted + teamCounts.updated,
          players: players.length,
          players_written: playerCounts.inserted + playerCounts.updated,
          players_skipped: playerCounts.skipped
        }
      };
    });
  }
  async function syncWeeklyProjections(week, taskOptions = {}) {
    const checked = assertWeek(week, "week");
    const context = contextFor(taskOptions, checked);
    const repository = repositoryFor(taskOptions);
    return runTask("weekly_projections", context, repository, async () => {
      const rows = await provider.fetchProjections(context);
      const counts = await repository.upsertProjections(rows);
      return {
        fetched: rows.length,
        counts: [counts],
        detail: { scoring_format: context.scoringFormat, season_type: context.seasonType }
      };
    });
  }
  async function syncBoxScores(week, taskOptions = {}) {
    const checked = assertWeek(week, "week");
    const context = contextFor(taskOptions, checked);
    const repository = repositoryFor(taskOptions);
    return runTask("box_scores", context, repository, async () => {
      const rows = await provider.fetchBoxScores(context);
      const counts = await repository.upsertWeeklyStats(rows);
      const games = new Set(rows.map((row) => row.game_external_id).filter(Boolean));
      return {
        fetched: rows.length,
        counts: [counts],
        detail: { games: games.size, scoring_format: context.scoringFormat }
      };
    });
  }
  async function syncSchedules(taskOptions = {}) {
    const requested = taskOptions.weeks === void 0 ? void 0 : (Array.isArray(taskOptions.weeks) ? taskOptions.weeks : [taskOptions.weeks]).map(
      (week) => assertWeek(week, "weeks[]")
    );
    const context = { ...contextFor(taskOptions), weeks: requested };
    const repository = repositoryFor(taskOptions);
    return runTask("schedules", context, repository, async () => {
      const games = await provider.fetchSchedules(context);
      const counts = await repository.upsertSchedules(games);
      const weeks = [...new Set(games.map((game) => game.week))].sort((a, b) => a - b);
      return {
        fetched: games.length,
        counts: [counts],
        detail: { weeks, week_count: weeks.length, requested_weeks: requested ?? "all" }
      };
    });
  }
  async function healthCheck() {
    try {
      const teams = await provider.fetchTeams(contextFor({}));
      const ok = teams.length > 0;
      if (!ok) logger.warn("health check: provider returned no teams");
      return { ok, provider: provider.name, teams: teams.length, errors: [] };
    } catch (error) {
      logger.error("health check failed", { error: error.message });
      return { ok: false, provider: provider.name, teams: 0, errors: [error.message] };
    }
  }
  function describe() {
    return provider.describe();
  }
  return {
    provider: provider.name,
    describe,
    healthCheck,
    syncPlayersAndRosters,
    syncWeeklyProjections,
    syncBoxScores,
    syncSchedules
  };
}

// lib/api/syncRoute.ts
var ALL_TASKS = ["players", "schedules", "projections", "boxscores"];
function json(body, status) {
  return new Response(JSON.stringify(body, null, 2), {
    status,
    headers: { "content-type": "application/json; charset=utf-8", "cache-control": "no-store" }
  });
}
function parseWeek(value, label) {
  if (!value) return void 0;
  const parsed = Number.parseInt(value, 10);
  if (!Number.isInteger(parsed) || parsed < 1 || parsed > 22) {
    throw new TypeError(`${label} must be an integer between 1 and 22, got "${value}"`);
  }
  return parsed;
}
function authorize(request, secret) {
  if (!secret) {
    return {
      ok: true,
      warning: "CRON_SECRET is not set \u2014 this route is protected only by the project\u2019s deployment protection. Add CRON_SECRET in the Vercel project settings."
    };
  }
  const header = request.headers.get("authorization") ?? "";
  const url = new URL(request.url);
  const presented = header.startsWith("Bearer ") ? header.slice(7) : url.searchParams.get("secret") ?? "";
  return { ok: presented === secret };
}
function weeklyPlan(focus) {
  const window = [.../* @__PURE__ */ new Set([focus.upcoming - 1, focus.upcoming, focus.upcoming + 1])].filter(
    (value) => value >= 1 && value <= 18
  );
  const plan = [
    { task: "players" },
    { task: "schedules", weeks: window },
    { task: "projections", week: focus.upcoming }
  ];
  if (focus.completed) plan.push({ task: "boxscores", week: focus.completed });
  return plan;
}
function planFor(params, focus, week, requestedWeeks) {
  const requested = (params.get("task") ?? "weekly").toLowerCase();
  if (requested === "weekly") return { plan: weeklyPlan(focus), mode: "weekly" };
  if (requested === "all") {
    return {
      plan: ALL_TASKS.map(
        (task) => task === "schedules" ? { task, weeks: requestedWeeks } : { task, week }
      ),
      mode: "all"
    };
  }
  const names = requested.split(",").map((name) => name.trim()).filter(Boolean);
  for (const name of names) {
    if (!ALL_TASKS.includes(name)) {
      throw new TypeError(
        `Unknown task "${name}". Use one of ${ALL_TASKS.join(", ")}, or "weekly" / "all".`
      );
    }
  }
  return {
    plan: names.map(
      (name) => name === "schedules" ? { task: "schedules", weeks: requestedWeeks } : { task: name, week }
    ),
    mode: names.join(",")
  };
}
async function handleSyncRequest(request, options = {}) {
  const startedAt = Date.now();
  const budgetMs = options.budgetMs ?? 55e3;
  const now = options.now ?? /* @__PURE__ */ new Date();
  const env = options.env ?? readEnv();
  const logger = options.logger ?? createLogger({ level: env.logLevel, json: true, bindings: { route: "/api/sync" } });
  const auth = authorize(request, process.env.CRON_SECRET ?? "");
  if (!auth.ok) {
    logger.warn("rejected an unauthorised sync request");
    return json({ ok: false, error: "unauthorized" }, 401);
  }
  if (auth.warning) logger.warn(auth.warning);
  const params = new URL(request.url).searchParams;
  const dryRun = ["1", "true", "yes"].includes((params.get("dry_run") ?? "").toLowerCase());
  let season;
  let focus;
  let week;
  let weeks;
  let plan;
  let mode;
  try {
    season = params.get("season") ? Number.parseInt(params.get("season"), 10) : env.season;
    if (!Number.isInteger(season) || season < 1920 || season > 2100) {
      throw new TypeError(`season must be a year between 1920 and 2100, got "${params.get("season")}"`);
    }
    focus = weekFocus(now, season === currentSeason(now) ? season : void 0);
    week = parseWeek(params.get("week"), "week") ?? env.weekOverride ?? focus.week;
    weeks = params.get("weeks") ? params.get("weeks").split(",").map((value) => parseWeek(value.trim(), "weeks[]")) : void 0;
    ({ plan, mode } = planFor(params, focus, week, weeks));
  } catch (error) {
    logger.warn("rejected a malformed sync request", { error: error.message });
    return json({ ok: false, error: error.message }, 400);
  }
  const service = options.service ?? createSportsDataService({ env: { ...env, season }, logger });
  const taskOptions = { season, dryRun: dryRun || env.dryRun };
  logger.info("scheduled sync starting", {
    mode,
    season,
    week,
    upcoming_week: focus.upcoming,
    completed_week: focus.completed,
    provider: service.provider,
    dry_run: taskOptions.dryRun,
    tasks: plan.length
  });
  const results = [];
  const skipped = [];
  for (const step of plan) {
    if (Date.now() - startedAt > budgetMs) {
      skipped.push(step.week ? `${step.task}:${step.week}` : step.task);
      continue;
    }
    switch (step.task) {
      case "players":
        results.push(await service.syncPlayersAndRosters(taskOptions));
        break;
      case "schedules":
        results.push(await service.syncSchedules({ ...taskOptions, weeks: step.weeks }));
        break;
      case "projections":
        results.push(await service.syncWeeklyProjections(step.week ?? week, taskOptions));
        break;
      case "boxscores":
        results.push(await service.syncBoxScores(step.week ?? week, taskOptions));
        break;
    }
  }
  const failed = results.filter((result) => !result.ok);
  const body = {
    ok: failed.length === 0 && skipped.length === 0,
    mode,
    provider: service.provider,
    season,
    week,
    focus,
    dry_run: taskOptions.dryRun,
    duration_ms: Date.now() - startedAt,
    written: results.reduce((total, result) => total + result.written, 0),
    fetched: results.reduce((total, result) => total + result.fetched, 0),
    tasks: results.map((result) => ({
      task: result.task,
      week: result.week,
      ok: result.ok,
      fetched: result.fetched,
      written: result.written,
      inserted: result.inserted,
      updated: result.updated,
      skipped: result.skipped,
      duration_ms: result.durationMs,
      run_id: result.runId,
      errors: result.errors
    })),
    skipped_tasks: skipped,
    warnings: auth.warning ? [auth.warning] : []
  };
  logger.info("scheduled sync finished", {
    ok: body.ok,
    written: body.written,
    failed: failed.length,
    skipped: skipped.length,
    ms: body.duration_ms
  });
  return json(body, body.ok ? 200 : 500);
}
function isWebRequest(value) {
  return typeof value === "object" && value !== null && typeof value.url === "string" && typeof value.headers?.get === "function";
}
function toWebRequest(request) {
  const host = request.headers["x-forwarded-host"] ?? request.headers.host ?? "localhost";
  const proto = request.headers["x-forwarded-proto"] ?? "https";
  const base = `${Array.isArray(proto) ? proto[0] : proto}://${Array.isArray(host) ? host[0] : host}`;
  const headers = new Headers();
  for (const [name, value] of Object.entries(request.headers)) {
    if (value === void 0) continue;
    headers.set(name, Array.isArray(value) ? value.join(", ") : value);
  }
  return new Request(new URL(request.url ?? "/", base), {
    method: request.method ?? "GET",
    headers
  });
}
async function send(response, result) {
  response.statusCode = result.status;
  result.headers.forEach((value, name) => response.setHeader(name, value));
  response.end(await result.text());
}
async function run(request) {
  try {
    return await handleSyncRequest(request);
  } catch (error) {
    const detail = error instanceof Error ? error.stack ?? error.message : String(error);
    process.stderr.write(`/api/sync crashed: ${detail}
`);
    return json({ ok: false, error: "sync route failed", detail: error.message }, 500);
  }
}
async function handler(request, response) {
  const result = await run(isWebRequest(request) ? request : toWebRequest(request));
  if (!response) return result;
  await send(response, result);
  return void 0;
}
export {
  handler as default,
  handleSyncRequest,
  weeklyPlan
};
